# Generated by Django 4.2.2 on 2023-12-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_birth_customuser_user_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='date_birth',
            new_name='birth_date',
        ),
    ]
