# Generated by Django 4.2.2 on 2023-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('Pets', 'Pets'), ('Travel', 'Travel'), ('Food', 'Food'), ('World', 'World'), ('Sport', 'Sport'), ('Lifestyle', 'Lifestyle'), ('Entertainment', 'Entertainment')], default='', max_length=15),
        ),
    ]
