# Generated by Django 4.2.2 on 2023-12-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
